import { type NextPage } from "next";
import Head from "next/head";
import { Box, Flex } from "@chakra-ui/react";
import Intro from "../components/Intro";
import PromptInput from "../components/PromptInput";
import Replies from "../components/Replies";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Metahelp.ai</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo-icon.png" type="image/png" />
      </Head>

      <main style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
        <Flex
          flexDir="column"
          alignItems="center"
          justifyContent="center"
          flex="1"
          h="100%"
          py={10}
          w="full"
          mx="auto"
          maxW="3xl"
          rowGap={12}>
          <Intro />
          <Replies />
          <PromptInput />
        </Flex>
      </main>
    </>
  );
};

export default Home;
